default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lionikis_family_photos
  password:

development:
  <<: *default
  database: lionikis_family_photos_development

test:
  <<: *default
  database: lionikis_family_photos_test
